export function gameColor(title: string): [string, string] {
  let h = 0;
  for (const c of title) h = (h * 31 + c.charCodeAt(0)) & 0xfffffff;
  const hue = h % 360;
  return [`hsl(${hue},22%,11%)`, `hsl(${(hue + 50) % 360},30%,18%)`];
}

export function initials(title: string): string {
  return title.split(' ').filter(w => /[A-Za-z0-9]/.test(w[0])).slice(0, 2).map(w => w[0].toUpperCase()).join('');
}

export function fmt(n: number | null): string {
  if (n == null) return '—';
  return n % 1 === 0 ? String(n) : n.toFixed(1);
}

export function pct(hrsIn: number, ttb: number): number {
  if (!ttb) return 0;
  return Math.min(100, Math.round((hrsIn / ttb) * 100));
}

export function isSteamCover(url: string | null | undefined): boolean {
  return url?.includes('steamstatic.com') ?? false;
}

// Identifies the generic cloudflare cover URL generated by the Steam sync.
// URLs from the appdetails API (Akamai CDN) don't match this pattern and
// should be preserved as-is — they are manually upgraded by the user or DetailModal.
export function isGenericSteamSyncCover(url: string | null | undefined): boolean {
  return Boolean(url?.startsWith('https://cdn.cloudflare.steamstatic.com/steam/apps/') && url?.endsWith('/header.jpg'));
}
